# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sagepilot.billing import billing_pb2 as sagepilot_dot_billing_dot_billing__pb2


class BillingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBillingSummary = channel.unary_unary(
                '/sagepilot.billing.BillingService/GetBillingSummary',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.BillingSummaryRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.BillingSummaryResponse.FromString,
                _registered_method=True)
        self.GetPlans = channel.unary_unary(
                '/sagepilot.billing.BillingService/GetPlans',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.GetPlansRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.GetPlansResponse.FromString,
                _registered_method=True)
        self.GetInvoices = channel.unary_unary(
                '/sagepilot.billing.BillingService/GetInvoices',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.GetInvoicesRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.GetInvoicesResponse.FromString,
                _registered_method=True)
        self.CreatePortalSession = channel.unary_unary(
                '/sagepilot.billing.BillingService/CreatePortalSession',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.CreatePortalSessionRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.CreatePortalSessionResponse.FromString,
                _registered_method=True)
        self.CreateCustomerSession = channel.unary_unary(
                '/sagepilot.billing.BillingService/CreateCustomerSession',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.CreateCustomerSessionRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.CreateCustomerSessionResponse.FromString,
                _registered_method=True)
        self.CheckEntitlement = channel.unary_unary(
                '/sagepilot.billing.BillingService/CheckEntitlement',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.CheckEntitlementRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.CheckEntitlementResponse.FromString,
                _registered_method=True)
        self.CheckUsageEligibility = channel.unary_unary(
                '/sagepilot.billing.BillingService/CheckUsageEligibility',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.CheckUsageEligibilityRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.CheckUsageEligibilityResponse.FromString,
                _registered_method=True)
        self.AuthorizeUsage = channel.unary_unary(
                '/sagepilot.billing.BillingService/AuthorizeUsage',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.AuthorizeUsageRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.AuthorizeUsageResponse.FromString,
                _registered_method=True)
        self.RecordUsageSync = channel.unary_unary(
                '/sagepilot.billing.BillingService/RecordUsageSync',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.RecordUsageSyncRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.RecordUsageSyncResponse.FromString,
                _registered_method=True)
        self.RecordUsageAsync = channel.unary_unary(
                '/sagepilot.billing.BillingService/RecordUsageAsync',
                request_serializer=sagepilot_dot_billing_dot_billing__pb2.RecordUsageAsyncRequest.SerializeToString,
                response_deserializer=sagepilot_dot_billing_dot_billing__pb2.RecordUsageAsyncResponse.FromString,
                _registered_method=True)


class BillingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBillingSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInvoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePortalSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCustomerSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckEntitlement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUsageEligibility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthorizeUsage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordUsageSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordUsageAsync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BillingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBillingSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBillingSummary,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.BillingSummaryRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.BillingSummaryResponse.SerializeToString,
            ),
            'GetPlans': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlans,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.GetPlansRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.GetPlansResponse.SerializeToString,
            ),
            'GetInvoices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInvoices,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.GetInvoicesRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.GetInvoicesResponse.SerializeToString,
            ),
            'CreatePortalSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePortalSession,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.CreatePortalSessionRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.CreatePortalSessionResponse.SerializeToString,
            ),
            'CreateCustomerSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCustomerSession,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.CreateCustomerSessionRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.CreateCustomerSessionResponse.SerializeToString,
            ),
            'CheckEntitlement': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckEntitlement,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.CheckEntitlementRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.CheckEntitlementResponse.SerializeToString,
            ),
            'CheckUsageEligibility': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUsageEligibility,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.CheckUsageEligibilityRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.CheckUsageEligibilityResponse.SerializeToString,
            ),
            'AuthorizeUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthorizeUsage,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.AuthorizeUsageRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.AuthorizeUsageResponse.SerializeToString,
            ),
            'RecordUsageSync': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordUsageSync,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.RecordUsageSyncRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.RecordUsageSyncResponse.SerializeToString,
            ),
            'RecordUsageAsync': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordUsageAsync,
                    request_deserializer=sagepilot_dot_billing_dot_billing__pb2.RecordUsageAsyncRequest.FromString,
                    response_serializer=sagepilot_dot_billing_dot_billing__pb2.RecordUsageAsyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sagepilot.billing.BillingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sagepilot.billing.BillingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BillingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBillingSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/GetBillingSummary',
            sagepilot_dot_billing_dot_billing__pb2.BillingSummaryRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.BillingSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/GetPlans',
            sagepilot_dot_billing_dot_billing__pb2.GetPlansRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.GetPlansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/GetInvoices',
            sagepilot_dot_billing_dot_billing__pb2.GetInvoicesRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.GetInvoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePortalSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/CreatePortalSession',
            sagepilot_dot_billing_dot_billing__pb2.CreatePortalSessionRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.CreatePortalSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCustomerSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/CreateCustomerSession',
            sagepilot_dot_billing_dot_billing__pb2.CreateCustomerSessionRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.CreateCustomerSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckEntitlement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/CheckEntitlement',
            sagepilot_dot_billing_dot_billing__pb2.CheckEntitlementRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.CheckEntitlementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUsageEligibility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/CheckUsageEligibility',
            sagepilot_dot_billing_dot_billing__pb2.CheckUsageEligibilityRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.CheckUsageEligibilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthorizeUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/AuthorizeUsage',
            sagepilot_dot_billing_dot_billing__pb2.AuthorizeUsageRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.AuthorizeUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordUsageSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/RecordUsageSync',
            sagepilot_dot_billing_dot_billing__pb2.RecordUsageSyncRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.RecordUsageSyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordUsageAsync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.billing.BillingService/RecordUsageAsync',
            sagepilot_dot_billing_dot_billing__pb2.RecordUsageAsyncRequest.SerializeToString,
            sagepilot_dot_billing_dot_billing__pb2.RecordUsageAsyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
