# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sagepilot.sage_engine import ai_service_pb2 as sagepilot_dot_sage__engine_dot_ai__service__pb2


class AIServiceStub(object):
    """============================================================================
    SERVICE DEFINITION
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitConversation = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/InitConversation',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.InitConversationRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.InitConversationResponse.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/GetConversation',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.GetConversationRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.GetConversationResponse.FromString,
                _registered_method=True)
        self.EndConversation = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/EndConversation',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.EndConversationRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.EndConversationResponse.FromString,
                _registered_method=True)
        self.Reply = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/Reply',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyResponse.FromString,
                _registered_method=True)
        self.ReplyStream = channel.unary_stream(
                '/sagepilot.sage_engine.AIService/ReplyStream',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyResponse.FromString,
                _registered_method=True)
        self.ConfirmResponse = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/ConfirmResponse',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmResponseRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmResponseResponse.FromString,
                _registered_method=True)
        self.ConfirmPartial = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/ConfirmPartial',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmPartialRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmPartialResponse.FromString,
                _registered_method=True)
        self.RejectTentative = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/RejectTentative',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.RejectTentativeRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.RejectTentativeResponse.FromString,
                _registered_method=True)
        self.AddMessage = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/AddMessage',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.AddMessageRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.AddMessageResponse.FromString,
                _registered_method=True)
        self.UpdateSystemPrompt = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/UpdateSystemPrompt',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.UpdateSystemPromptRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.UpdateSystemPromptResponse.FromString,
                _registered_method=True)
        self.ClearHistory = channel.unary_unary(
                '/sagepilot.sage_engine.AIService/ClearHistory',
                request_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ClearHistoryRequest.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ClearHistoryResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """============================================================================
    SERVICE DEFINITION
    ============================================================================

    """

    def InitConversation(self, request, context):
        """Conversation lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reply(self, request, context):
        """AI replies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmResponse(self, request, context):
        """Response lifecycle (for interrupt handling)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmPartial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectTentative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMessage(self, request, context):
        """Conversation control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSystemPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.InitConversation,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.InitConversationRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.InitConversationResponse.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.GetConversationRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.GetConversationResponse.SerializeToString,
            ),
            'EndConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.EndConversation,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.EndConversationRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.EndConversationResponse.SerializeToString,
            ),
            'Reply': grpc.unary_unary_rpc_method_handler(
                    servicer.Reply,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyResponse.SerializeToString,
            ),
            'ReplyStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ReplyStream,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyResponse.SerializeToString,
            ),
            'ConfirmResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmResponse,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmResponseRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmResponseResponse.SerializeToString,
            ),
            'ConfirmPartial': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmPartial,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmPartialRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmPartialResponse.SerializeToString,
            ),
            'RejectTentative': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectTentative,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.RejectTentativeRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.RejectTentativeResponse.SerializeToString,
            ),
            'AddMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMessage,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.AddMessageRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.AddMessageResponse.SerializeToString,
            ),
            'UpdateSystemPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSystemPrompt,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.UpdateSystemPromptRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.UpdateSystemPromptResponse.SerializeToString,
            ),
            'ClearHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearHistory,
                    request_deserializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ClearHistoryRequest.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_ai__service__pb2.ClearHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sagepilot.sage_engine.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sagepilot.sage_engine.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """============================================================================
    SERVICE DEFINITION
    ============================================================================

    """

    @staticmethod
    def InitConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/InitConversation',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.InitConversationRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.InitConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/GetConversation',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.GetConversationRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.GetConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/EndConversation',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.EndConversationRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.EndConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/Reply',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplyStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sagepilot.sage_engine.AIService/ReplyStream',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/ConfirmResponse',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmResponseRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmResponseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmPartial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/ConfirmPartial',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmPartialRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ConfirmPartialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectTentative(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/RejectTentative',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.RejectTentativeRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.RejectTentativeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/AddMessage',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.AddMessageRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.AddMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSystemPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/UpdateSystemPrompt',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.UpdateSystemPromptRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.UpdateSystemPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.sage_engine.AIService/ClearHistory',
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ClearHistoryRequest.SerializeToString,
            sagepilot_dot_sage__engine_dot_ai__service__pb2.ClearHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
