# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sagepilot/sage_engine/example.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'sagepilot/sage_engine/example.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#sagepilot/sage_engine/example.proto\x12\x07\x65xample\"\x1d\n\x07Request\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"&\n\x08Response\x12\x1a\n\x08greeting\x18\x01 \x01(\tR\x08greeting2:\n\x07Greeter\x12/\n\x08SayHello\x12\x10.example.Request\x1a\x11.example.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sagepilot.sage_engine.example_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=48
  _globals['_REQUEST']._serialized_end=77
  _globals['_RESPONSE']._serialized_start=79
  _globals['_RESPONSE']._serialized_end=117
  _globals['_GREETER']._serialized_start=119
  _globals['_GREETER']._serialized_end=177
# @@protoc_insertion_point(module_scope)
