# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sagepilot.sage_engine import example_pb2 as sagepilot_dot_sage__engine_dot_example__pb2


class GreeterStub(object):
    """Define a service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/example.Greeter/SayHello',
                request_serializer=sagepilot_dot_sage__engine_dot_example__pb2.Request.SerializeToString,
                response_deserializer=sagepilot_dot_sage__engine_dot_example__pb2.Response.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """Define a service
    """

    def SayHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=sagepilot_dot_sage__engine_dot_example__pb2.Request.FromString,
                    response_serializer=sagepilot_dot_sage__engine_dot_example__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('example.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Define a service
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/example.Greeter/SayHello',
            sagepilot_dot_sage__engine_dot_example__pb2.Request.SerializeToString,
            sagepilot_dot_sage__engine_dot_example__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
