# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sagepilot.databaseaccess import databaseaccess_pb2 as sagepilot_dot_databaseaccess_dot_databaseaccess__pb2


class DatabaseAccessStub(object):
    """DatabaseAccess is the centralized database access service.
    All database operations from other services should go through this service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/sagepilot.databaseaccess.DatabaseAccess/Query',
                request_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryRequest.SerializeToString,
                response_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.QueryOne = channel.unary_unary(
                '/sagepilot.databaseaccess.DatabaseAccess/QueryOne',
                request_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryRequest.SerializeToString,
                response_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.RowResponse.FromString,
                _registered_method=True)
        self.QueryValue = channel.unary_unary(
                '/sagepilot.databaseaccess.DatabaseAccess/QueryValue',
                request_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryRequest.SerializeToString,
                response_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ValueResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/sagepilot.databaseaccess.DatabaseAccess/Execute',
                request_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.BulkInsert = channel.unary_unary(
                '/sagepilot.databaseaccess.DatabaseAccess/BulkInsert',
                request_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.BulkInsertRequest.SerializeToString,
                response_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/sagepilot.databaseaccess.DatabaseAccess/Health',
                request_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.HealthRequest.SerializeToString,
                response_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.HealthResponse.FromString,
                _registered_method=True)


class DatabaseAccessServicer(object):
    """DatabaseAccess is the centralized database access service.
    All database operations from other services should go through this service.
    """

    def Query(self, request, context):
        """Query executes a SQL query and returns multiple rows
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryOne(self, request, context):
        """QueryOne executes a SQL query and returns a single row
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryValue(self, request, context):
        """QueryValue executes a SQL query and returns a single value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Execute runs a SQL statement (INSERT, UPDATE, DELETE) and returns affected rows
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkInsert(self, request, context):
        """BulkInsert performs bulk insert operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health returns the health status of the database pools
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseAccessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryRequest.FromString,
                    response_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryResponse.SerializeToString,
            ),
            'QueryOne': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOne,
                    request_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryRequest.FromString,
                    response_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.RowResponse.SerializeToString,
            ),
            'QueryValue': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryValue,
                    request_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryRequest.FromString,
                    response_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ValueResponse.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ExecuteRequest.FromString,
                    response_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ExecuteResponse.SerializeToString,
            ),
            'BulkInsert': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkInsert,
                    request_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.BulkInsertRequest.FromString,
                    response_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ExecuteResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.HealthRequest.FromString,
                    response_serializer=sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sagepilot.databaseaccess.DatabaseAccess', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sagepilot.databaseaccess.DatabaseAccess', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseAccess(object):
    """DatabaseAccess is the centralized database access service.
    All database operations from other services should go through this service.
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.databaseaccess.DatabaseAccess/Query',
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryRequest.SerializeToString,
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryOne(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.databaseaccess.DatabaseAccess/QueryOne',
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryRequest.SerializeToString,
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.RowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.databaseaccess.DatabaseAccess/QueryValue',
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.QueryRequest.SerializeToString,
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.databaseaccess.DatabaseAccess/Execute',
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ExecuteRequest.SerializeToString,
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkInsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.databaseaccess.DatabaseAccess/BulkInsert',
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.BulkInsertRequest.SerializeToString,
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sagepilot.databaseaccess.DatabaseAccess/Health',
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.HealthRequest.SerializeToString,
            sagepilot_dot_databaseaccess_dot_databaseaccess__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
